' This file is automatically generated by the GIS Prebuild project 
Imports System.Reflection 
Imports System.Runtime.CompilerServices 
Imports System.Runtime.InteropServices 
'  
<Assembly: AssemblyVersion("1.5.2.0")> 
<Assembly: AssemblyFileVersion("1.5.2.0")> 
