// This file is automatically generated by the GIS Prebuild project 
using System.Reflection; 
using System.Runtime.CompilerServices; 
using System.Runtime.InteropServices;
 //  
[assembly: AssemblyVersion("1.5.2.0")] 
[assembly: AssemblyFileVersion("1.5.2.0")] 
